### PR TITLE
WIP Colours

### PR DESCRIPTION
**Pull request by curran**
(WIP = Work in Progress, not ready for review/merge)

### CODE REVIEW

**Comment by curran** [comment]
image

**Comment by curran** [comment]
Up next here:

 * [ ] Figure out a way to re-produce the design in #25 for a single box.
 * [ ] Re-create all variations (with outer box, without outer box)
 * [ ] Encode the full layout

**Comment by curran** [comment]
Relating to the color discussion in #30 , in JavaScript we should probably also use the naming convention of "blue100"

If we need to programmatically generate in-between colors, this feature of linear scales might be useful:

```js
var color = d3.scaleLinear()
    .domain([-1, 0, 1])
    .range(["red", "white", "green"]);

color(-0.5); // "rgb(255, 128, 128)"
color(+0.5); // "rgb(128, 192, 128)"
```

**Comment by vidonne** [comment]
I think it makes sense to calculate them we just have to make sure we got the same results.

**Comment by curran** [comment]
My idea is to use the standardised colors for the  @blue100, @blue200 , etc., and only calculate the in-between colors if we need them, like @blue129 for example.

**Comment by matthewsmawfield** [comment]
@curran i think this satisfies the concerns and we can proceed.

**Comment by curran** [comment]
Closing in favor of https://github.com/unhcr/dataviz-styleguide/pull/82

**Pull request closed without merging**
